Healthy/Controllers/EntriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Healthy.Data;
using Healthy.Models;
using System.Diagnostics;
using System.Security.Claims;

namespace GetHealthy.Controllers
{
    [Authorize]
    public class EntriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EntriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Entries
        [Authorize]

        public async Task<IActionResult> Index()
        {
            var today = DateTime.Today;
            var currentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.Entry.Include(e => e.Food).Include(e => e.User).Where(e => e.IntakeTime.Date == today).Where(e => e.IdentityUserId == currentUserID);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Entries/Details/5
        [Authorize]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.Entry
                .Include(e => e.Food)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entry == null)
            {
                return NotFound();
            }

            return View(entry);
        }

        // GET: Entries/Create
        [Authorize]

        public IActionResult Create()
        {
            PopulateSelectLists();
            return View();
        }

        // POST: Entries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,MealType,Ate,Quantity,FoodId,IntakeTime")] Entry entry)
        {
            entry.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            entry.IntakeTime = DateTime.Today.Add(entry.IntakeTime.TimeOfDay);
            entry.Name = "Intake";

            _context.Add(entry);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private void PopulateSelectLists(object selectedFood = null)
        {
            var foodsQuery = from f in _context.Food
                             orderby f.Name
                             select f;
            ViewBag.FoodList = new SelectList(foodsQuery.AsNoTracking(), "Id", "Name", selectedFood);
        }

        // GET: Entries/Edit/5
        [Authorize]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.Entry.FindAsync(id);
            entry.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            entry.IntakeTime = DateTime.Today.Add(entry.IntakeTime.TimeOfDay);
            entry.Name = "Intake";

            PopulateSelectLists(entry.FoodId);
            return View(entry);
        }

        // POST: Entries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,MealType,Ate,Quantity,FoodId,IntakeTime,IdentityUserId")] Entry entry)
        {
            if (id != entry.Id)
            {
                return NotFound();
            }
            entry.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            entry.Name = "Intake";
            entry.IntakeTime = DateTime.Today.Add(entry.IntakeTime.TimeOfDay);
            try
            {
                _context.Update(entry);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EntryExists(entry.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Entries/Delete/5
        [Authorize]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.Entry
                .Include(e => e.Food)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entry == null)
            {
                return NotFound();
            }

            return View(entry);
        }

        // POST: Entries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entry = await _context.Entry.FindAsync(id);
            if (entry != null)
            {
                _context.Entry.Remove(entry);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> ToggleAte(int id, bool ate)
        {
            var entry = await _context.Entry.FindAsync(id);
            if (entry == null)
            {
                return NotFound();
            }

            entry.Ate = ate;
            _context.Update(entry);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        // GET: Entries/History
        [Authorize]

        public async Task<IActionResult> History()
        {
            var currentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.Entry
            .Include(e => e.Food)
            .Include(e => e.User)
            .Where(e => e.IdentityUserId == currentUserID);

            return View(await applicationDbContext.ToListAsync());
        }

        private bool EntryExists(int id)
        {
            return _context.Entry.Any(e => e.Id == id);
        }
    }
}

Healthy/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Healthy.Data;
using Healthy.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
//using GetHealthy.Data.Migrations;

namespace GetHealthy.Controllers
{
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Foods
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.Food.Include(e => e.User).Where(e => e.IdentityUserId == currentUserID);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Foods/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Reference,Calories,Fat,Carbs,Protein")] Food food)
        {
            food.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _context.Add(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Foods/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var food = await _context.Food.FindAsync(id);
            food.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Reference,Calories,Fat,Carbs,Protein")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }
            food.IdentityUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {
                _context.Update(food);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FoodExists(food.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Foods/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Food.FindAsync(id);
            if (food != null)
            {
                var relatedEntries = _context.Entry.Where(e => e.FoodId == id);
                _context.Entry.RemoveRange(relatedEntries);
                _context.Food.Remove(food);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Food.Any(e => e.Id == id);
        }
    }
}

Healthy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Get Healthy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/styles.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="~/Healthy.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/Assets/avocado.ico" type="image/x-icon" />

    <!-- FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Leckerli+One&family=Love+Ya+Like+A+Sister&family=Pacifico&display=swap" rel="stylesheet">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Today</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Foods" asp-action="Index">Food</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Entries" asp-action="History">History</a>
                            </li>
                        }
                    </ul>
                     <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Assets/avocado.ico" width="35px" height="35px"/>Get Healthy</a>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container centered">
            &copy; 2024 - Get Healthy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>